# Generated by Django 6.0.3 on 2026-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('telegram_number', models.CharField(db_index=True, max_length=20)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
                ('broker_account_number', models.CharField(db_index=True, max_length=50)),
                ('broker_server', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_id'],
                'indexes': [models.Index(fields=['client_id'], name='client_clie_client__5d32ef_idx'), models.Index(fields=['telegram_number'], name='client_clie_telegra_d8cd6e_idx'), models.Index(fields=['channel_id'], name='client_clie_channel_f1350a_idx'), models.Index(fields=['broker_account_number', 'broker_server'], name='client_clie_broker__d295f5_idx'), models.Index(fields=['is_active'], name='client_clie_is_acti_b9e0de_idx')],
            },
        ),
    ]
