# Generated by Django 6.0.3 on 2026-03-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('replied_message_id', models.CharField(blank=True, max_length=255)),
                ('replied_text', models.TextField(blank=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_messages', to='client.clientconfig')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['client', 'message_id'], name='client_webh_client__0fa436_idx'), models.Index(fields=['client', 'received_at'], name='client_webh_client__952bb7_idx')],
            },
        ),
    ]
