# Generated by Django 6.0.3 on 2026-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_webhookmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookmessage',
            name='channel_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
