# Generated by Django 6.0.3 on 2026-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('telegram_number', models.CharField(db_index=True, max_length=20)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
                ('broker_account_number', models.CharField(db_index=True, max_length=50)),
                ('broker_server', models.CharField(db_index=True, max_length=100)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('replied_message_id', models.CharField(blank=True, max_length=255)),
                ('replied_text', models.TextField(blank=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['client_id', 'message_id'], name='parser_webh_client__2fddf2_idx'), models.Index(fields=['channel_id', 'message_id'], name='parser_webh_channel_39f96f_idx'), models.Index(fields=['received_at'], name='parser_webh_receive_afdc58_idx')],
            },
        ),
    ]
