# Generated by Django 6.0.3 on 2026-03-16 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_webhookmessage'),
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='channel_config', serialize=False, to='client.clientconfig')),
                ('kw_entry_point', models.CharField(blank=True, default='', help_text='Word provider uses for entry price (e.g. OPEN). Blank = auto-detect from BUY/SELL or ENPRICE line.', max_length=200, verbose_name='Entry Point')),
                ('kw_buy', models.CharField(blank=True, default='', help_text='Comma-separated aliases (e.g. LONG,B).', max_length=200, verbose_name='BUY aliases')),
                ('kw_sell', models.CharField(blank=True, default='', help_text='Comma-separated aliases (e.g. SHORT,S).', max_length=200, verbose_name='SELL aliases')),
                ('kw_sl', models.CharField(blank=True, default='', help_text='Comma-separated aliases (e.g. STOP,STOP-LOSS).', max_length=200, verbose_name='SL aliases')),
                ('kw_tp', models.CharField(blank=True, default='', help_text='Comma-separated aliases (e.g. TARGET,PROFIT).', max_length=200, verbose_name='TP aliases')),
                ('kw_market_order', models.CharField(blank=True, default='', help_text='Forces market execution even when a limit price is given.', max_length=200, verbose_name='Market Order keyword')),
                ('use_ai', models.BooleanField(default=False, help_text='GPT-based signal parsing (requires AI subscription).', verbose_name='AI parsing')),
                ('read_image', models.BooleanField(default=False, help_text='OCR extraction from image messages (requires subscription).', verbose_name='Read images')),
                ('kw_close_tp1', models.CharField(blank=True, default='', max_length=200, verbose_name='Close TP1')),
                ('kw_close_tp2', models.CharField(blank=True, default='', max_length=200, verbose_name='Close TP2')),
                ('kw_close_tp3', models.CharField(blank=True, default='', max_length=200, verbose_name='Close TP3')),
                ('kw_close_tp4', models.CharField(blank=True, default='', max_length=200, verbose_name='Close TP4')),
                ('kw_close_full', models.CharField(blank=True, default='', help_text='Reply keyword that closes the entire position.', max_length=200, verbose_name='Close Full')),
                ('kw_close_half', models.CharField(blank=True, default='', max_length=200, verbose_name='Close Half')),
                ('kw_close_partial', models.CharField(blank=True, default='', max_length=200, verbose_name='Close Partial')),
                ('kw_breakeven', models.CharField(blank=True, default='', help_text='Move SL to entry price.', max_length=200, verbose_name='Break Even')),
                ('kw_set_tp1', models.CharField(blank=True, default='', max_length=200, verbose_name='Set TP1')),
                ('kw_set_tp2', models.CharField(blank=True, default='', max_length=200, verbose_name='Set TP2')),
                ('kw_set_tp3', models.CharField(blank=True, default='', max_length=200, verbose_name='Set TP3')),
                ('kw_set_tp4', models.CharField(blank=True, default='', max_length=200, verbose_name='Set TP4')),
                ('kw_set_tp5', models.CharField(blank=True, default='', max_length=200, verbose_name='Set TP5')),
                ('kw_set_all_tp', models.CharField(blank=True, default='', max_length=200, verbose_name='Set All TPs')),
                ('kw_set_sl', models.CharField(blank=True, default='', max_length=200, verbose_name='Set SL')),
                ('kw_delete_pending', models.CharField(blank=True, default='', max_length=200, verbose_name='Delete pending order')),
                ('kw_layer', models.CharField(blank=True, default='', max_length=200, verbose_name='Layer / re-entry')),
                ('kw_close_all', models.CharField(blank=True, default='', max_length=200, verbose_name='Close All')),
                ('kw_delete_all', models.CharField(blank=True, default='', max_length=200, verbose_name='Delete All')),
                ('kw_ignore', models.CharField(blank=True, default='', help_text='Any message containing this word is ignored entirely.', max_length=200, verbose_name='Ignore keyword')),
                ('kw_skip', models.CharField(blank=True, default='', help_text='Text between skip markers is stripped before parsing.', max_length=200, verbose_name='Skip keyword')),
                ('kw_remove_sl', models.CharField(blank=True, default='', max_length=200, verbose_name='Remove SL')),
                ('delay_ms', models.PositiveIntegerField(default=0, help_text='Milliseconds to wait before dispatching the signal.', verbose_name='Delay (ms)')),
                ('prefer_entry', models.IntegerField(choices=[(0, 'First Price'), (1, 'Second Price'), (2, 'Average Price'), (3, 'ALL Price — one signal per entry')], default=0, help_text='Which price to use when a range is given (e.g. 2330/2335).', verbose_name='Prefer Entry')),
                ('sl_in_pips', models.BooleanField(default=False, verbose_name='SL in Pips')),
                ('tp_in_pips', models.BooleanField(default=False, verbose_name='TP in Pips')),
                ('delimiters', models.CharField(blank=True, default='', help_text="Two-char pair; enclosed text is stripped before parsing (e.g. '[]').", max_length=10, verbose_name='Delimiters')),
                ('all_order', models.BooleanField(default=False, help_text='Execute both market AND pending orders.', verbose_name='ALL Order')),
                ('read_forwarded', models.BooleanField(default=True, help_text='False → ignore forwarded Telegram messages.', verbose_name='Read Forwarded')),
                ('news_filter', models.BooleanField(default=False, help_text='Block new signals during high-impact news windows.', verbose_name='News Filter')),
            ],
            options={
                'verbose_name': 'Channel Config',
                'verbose_name_plural': 'Channel Configs',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tp_count', models.PositiveIntegerField(default=5, help_text='Max TPs per signal. 0 = unlimited.')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ParsedSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', 'Open'), ('edit', 'Edit'), ('close', 'Close'), ('closeall', 'Close All'), ('deleteall', 'Delete All'), ('closehalf', 'Close Half'), ('closehalfbe', 'Close Half + BE'), ('closepartial', 'Close Partial'), ('closepartialbe', 'Close Partial + BE'), ('update', 'Update SL/TP'), ('breakeven', 'Breakeven'), ('delete', 'Delete Pending')], db_index=True, default='open', max_length=20)),
                ('symbol', models.CharField(blank=True, default='', help_text='Trading pair / instrument (e.g. XAUUSD).', max_length=32)),
                ('direction', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='', help_text='BUY or SELL. Blank for non-open kinds (close, update, …).', max_length=4)),
                ('entry_price', models.CharField(blank=True, default='', help_text='Empty = market order.', max_length=32)),
                ('sl_value', models.CharField(blank=True, default='0', help_text="'0' = no SL. May carry ' pips' suffix when sl_in_pips is set.", max_length=32, verbose_name='Stop-Loss')),
                ('command_text', models.TextField(blank=True, default='', help_text='Full command dispatched to the MT4/MT5 signal file.')),
                ('output_filename', models.CharField(blank=True, default='', help_text='Filename of the signal file written to disk.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Parse Error')], db_index=True, default='PENDING', max_length=12)),
                ('blocked_by_news_filter', models.BooleanField(default=False, help_text='True → suppressed by news-window filter; file not written.')),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='The raw webhook message this signal was parsed from.', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_signals', to='parser.webhookmessage')),
            ],
            options={
                'verbose_name': 'Parsed Signal',
                'verbose_name_plural': 'Parsed Signals',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='TakeProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='TP sequence number (1-based).', validators=[django.core.validators.MinValueValidator(1)])),
                ('value', models.CharField(help_text="Price level or '<N> pips'. '-1' = not set / unchanged.", max_length=32)),
                ('hit_at', models.DateTimeField(blank=True, help_text='Timestamp when this TP was hit and the position partially closed.', null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_profits', to='parser.parsedsignal')),
            ],
            options={
                'verbose_name': 'Take Profit',
                'verbose_name_plural': 'Take Profits',
                'ordering': ['signal', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='parsedsignal',
            index=models.Index(fields=['symbol', 'direction'], name='parser_pars_symbol_01ffdc_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedsignal',
            index=models.Index(fields=['kind'], name='parser_pars_kind_c772ad_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedsignal',
            index=models.Index(fields=['parsed_at'], name='parser_pars_parsed__46a93f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='takeprofit',
            unique_together={('signal', 'order')},
        ),
    ]
