# Generated by Django 6.0.3 on 2026-03-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_channelconfig_systemsettings_parsedsignal_takeprofit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takeprofit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parsedsignal',
            name='output_filename',
        ),
        migrations.RemoveField(
            model_name='parsedsignal',
            name='sl_value',
        ),
        migrations.AddField(
            model_name='parsedsignal',
            name='close_tp',
            field=models.CharField(blank=True, default='', help_text='TP label targeted by a close command (e.g. TP1).', max_length=8),
        ),
        migrations.AddField(
            model_name='parsedsignal',
            name='new_sl',
            field=models.CharField(blank=True, default='', help_text='New SL requested by update/edit. Empty if unchanged.', max_length=32),
        ),
        migrations.AddField(
            model_name='parsedsignal',
            name='sl',
            field=models.CharField(blank=True, default='0', help_text="'0' = no SL. May carry ' pips' suffix.", max_length=32, verbose_name='Stop-Loss'),
        ),
        migrations.AddField(
            model_name='takeprofit',
            name='is_edit_target',
            field=models.BooleanField(default=False, help_text='True → this TP was set/changed by an update command, not from the original open signal.'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='delimiters',
            field=models.CharField(blank=True, default='', help_text="Two-char pair; enclosed text stripped before parsing (e.g. '[]').", max_length=10, verbose_name='Delimiters'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_close_full',
            field=models.CharField(blank=True, default='', help_text='Reply keyword to close the entire position.', max_length=200, verbose_name='Close Full'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_entry_point',
            field=models.CharField(blank=True, default='', help_text='Word provider uses for entry price (e.g. OPEN). Blank = auto-detect.', max_length=200, verbose_name='Entry Point'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_ignore',
            field=models.CharField(blank=True, default='', help_text='Messages containing this word are ignored entirely.', max_length=200, verbose_name='Ignore keyword'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='prefer_entry',
            field=models.IntegerField(choices=[(0, 'First Price'), (1, 'Second Price'), (2, 'Average Price'), (3, 'ALL Price — one signal per entry in range')], default=0, help_text='Which price to use when a range is given (e.g. 2330/2335).', verbose_name='Prefer Entry'),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='blocked_by_news_filter',
            field=models.BooleanField(default=False, help_text='True → suppressed by news-window filter; command not dispatched.'),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='command_text',
            field=models.TextField(blank=True, default='', help_text='Full command string  e.g. /open USDJPY,SELL,1.54,0,1111,…'),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='direction',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='', help_text='BUY or SELL. Blank for non-open kinds.', max_length=4),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='entry_price',
            field=models.CharField(blank=True, default='', help_text='Entry price string. Empty = market order.', max_length=32),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='message',
            field=models.ForeignKey(help_text='Source webhook message.', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_signals', to='parser.webhookmessage'),
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='symbol',
            field=models.CharField(blank=True, default='', help_text='Instrument symbol (e.g. XAUUSD, USDJPY).', max_length=32),
        ),
        migrations.AlterField(
            model_name='takeprofit',
            name='hit_at',
            field=models.DateTimeField(blank=True, help_text='When this TP was hit and the position partially closed.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='takeprofit',
            unique_together={('signal', 'order', 'is_edit_target')},
        ),
    ]
