# Generated by Django 6.0.3 on 2026-03-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_webhookmessage'),
        ('parser', '0003_alter_takeprofit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookmessage',
            name='parser_webh_client__2fddf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookmessage',
            name='parser_webh_channel_39f96f_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookmessage',
            name='parser_webh_receive_afdc58_idx',
        ),
        migrations.AlterField(
            model_name='parsedsignal',
            name='message',
            field=models.ForeignKey(help_text='Source webhook message.', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_signals', to='client.webhookmessage'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_buy',
            field=models.CharField(blank=True, default='LONG', help_text='Comma-separated aliases (e.g. LONG,B).', max_length=200, verbose_name='BUY aliases'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_entry_point',
            field=models.CharField(blank=True, default='ENTRY', help_text='Word provider uses for entry price. Default: ENTRY.', max_length=200, verbose_name='Entry Point'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_sell',
            field=models.CharField(blank=True, default='SHORT', help_text='Comma-separated aliases (e.g. SHORT,S).', max_length=200, verbose_name='SELL aliases'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_sl',
            field=models.CharField(blank=True, default='SL', help_text='Comma-separated aliases (e.g. STOP,STOP-LOSS).', max_length=200, verbose_name='SL aliases'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='kw_tp',
            field=models.CharField(blank=True, default='TP', help_text='Comma-separated aliases (e.g. TARGET,PROFIT).', max_length=200, verbose_name='TP aliases'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='prefer_entry',
            field=models.IntegerField(choices=[(0, 'First Price'), (1, 'Second Price'), (2, 'Average Price'), (3, 'ALL Price — one signal per entry in range')], default=2, help_text='Which price to use when a range is given (e.g. 2330/2335).', verbose_name='Prefer Entry'),
        ),
        migrations.DeleteModel(
            name='WebhookMessage',
        ),
    ]
