# Generated by Django 6.0.3 on 2026-03-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_webhookmessage_channel_id'),
        ('parser', '0004_remove_webhookmessage_parser_webh_client__2fddf2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='channel_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Telegram channel ID for this configuration.', max_length=100, verbose_name='Channel ID'),
        ),
        migrations.AddField(
            model_name='channelconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='client.clientconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='channelconfig',
            unique_together={('client', 'channel_id')},
        ),
    ]
